In [42]:
import numpy as np
import scipy.linalg

### Задание 1
Решить линейную систему
$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 0 & 6 \\ 7 & 8 & 9 \end{bmatrix} \cdot X = \begin{bmatrix} 12 \\ 2 \\ 1 \end{bmatrix}$

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

### Задание 2
Найдите псевдорешение:

x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15

In [4]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond=-1)

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

Посмотрим отклонения от реальных значений.

In [6]:
np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ]) - B

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])

### Задание 3
Сколько решений имеет линейная система $\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} \cdot X = \begin{bmatrix} 12 \\ 2 \\ 1 \end{bmatrix}$

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.

Просчитаем определитель этой матрицы.

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
np.linalg.det(A)

-9.51619735392994e-16

Конечно с погрешностью, но видим что определитель матрицы равен 0 (проверил вручную). Напишем расширенную матрицу и посчитаем ранги исходной и расширенной.

In [33]:
C = np.concatenate((A,B.T), axis=1)
print(C)
np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

Видим что ранг расширенной матрицы больше чем исходной. Следовательно решений нет. Видно что строки матрицы отличаются одна от другой на 3. Изменим правую часть на (12, 15, 18) чтобы было соответствие с левой частью. Так же составим расширенную матрицу с новыми значениями.

In [34]:
D = np.array([[12, 15, 18]])
E = np.concatenate((A, D.T), axis=1)
print(E)
np.linalg.matrix_rank(A), np.linalg.matrix_rank(E)

[[ 1  2  3 12]
 [ 4  5  6 15]
 [ 7  8  9 18]]


(2, 2)

Тперь ранг матриц совпадает и следовательно имеется бесконечно много решений.

### Задание 4
Вычислите LU-разложение матрицы: $\begin{bmatrix} 1 & 2 & 3 \\ 2 & 16 & 21 \\ 4 & 28 & 73 \end{bmatrix}$

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

Проверим что определитель матрицы не равен нулю.

In [37]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
np.linalg.det(A)

432.00000000000017

Определитель не равен 0 и матрица имеет единственное решение.

Теперь вычислим LU-разложение.

In [43]:
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


Возьмем вектор правых частей равный $B = \begin{bmatrix} 1 \\ 2 \\ 4 \end{bmatrix}$. А затем найдем решение.

In [50]:
B = np.array([1, 2, 4])
np.linalg.solve(A, B)

array([ 1., -0., -0.])